### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by Matej-Hajek** [alt-lite3dp/Lite3DP-S1#5]
[The README is here](https://github.com/Matej-Hajek/Lite3DP-S1/tree/readme-update#readme)
Updated README.
Includes the original license at the end.
Includes the ["FAQs"](https://github.com/alt-lite3dp/Lite3DP-S1#faqs).
Added useful links, and info from [Lite3DP crowdsupply](https://www.crowdsupply.com/lite3dp/lite3dp-3d-printer).

I don´t know if there is too much info, or if this type of info should be in a GitHub repo wiki (wiki could be useful). But in this README is like 99% of info about the project and printer.

**Comment by eduncan911** [comment]
I prefer to do exactly what you did, which is a great start.  However, we have to take into consideration the original author's copyright claim, as it is copyrighted.  Says so in the text you removed:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

So it has to go back.  Now, we can have multiple licenses and would very much like it to be GNU instead of MIT.  But I wanted to open that to public discussion first.

As for formatting, I have no opinion at this time.  Anything is better than nothing!

**Comment by Matej-Hajek** [comment]
Just added the original license back. Also closed #4.
> I prefer to do exactly what you did, which is a great start. However, we have to take into consideration the original author's copyright claim, as it is copyrighted. Says so in the text you removed:

**Comment by eduncan911** [comment]
Was resolved in #6
